# Generated by Django 3.2.6 on 2021-08-30 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_auto_20210831_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='addr',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mname',
            new_name='middlename',
        ),
    ]
